import { CsvParseStream } from "jsr:@std/csv/parse-stream";

const res = await fetch("https://wago.tools/db2/mawpower/csv");
const csvStream = res.body!
	.pipeThrough(new TextDecoderStream())
	.pipeThrough(new CsvParseStream({ skipFirstRow: true }));

const lines = [];
for await (const row of csvStream) {
  lines.push(`\t[${row.ID}] = ${row.SpellID}`);
}

const out = `local _, addon = ...;

-- This file is generated by the update script. Do not edit.

local mawpower = {
${lines.join(",\n")}
};

function addon.GetMawPowerSpellID(id)
	return mawpower[id];
end
`;

Deno.writeFile("data/mawpower.lua", new TextEncoder().encode(out));
console.log("updated: mawpower.lua");
