import { readCSVObjects } from "https://deno.land/x/csv@v0.8.0/mod.ts";

const f = await Deno.open("scripts/data/mawpower.csv");

const lines = [];
for await (const row of readCSVObjects(f)) {
  lines.push(`\t[${row.ID}] = ${row.SpellID}`);
}

f.close();

const out = `local _, addon = ...;

-- This file is generated by the update script. Do not edit.

local mawpower = {
${lines.join(",\n")}
};

function addon.GetMawPowerSpellID(id)
	return mawpower[id];
end
`;

Deno.writeFile("data/mawpower.lua", new TextEncoder().encode(out));
console.log("updated: mawpower.lua");
