import fetchDBC from "../utils/fetch-dbc.ts";

interface MawPower {
	ID: number,
	SpellID: number,
	MawPowerRarityID: number
}

const { build, data } = await fetchDBC<MawPower>("mawpower");

const out = `local _, addon = ...;

-- This file is generated by the update script. Do not edit.
-- Data based on build ${build}

local mawpower = {
${data.map((entry) => `\t[${entry.ID}] = ${entry.SpellID}`).join(',\n')}
};

function addon.GetMawPowerSpellID(id)
	return mawpower[id];
end
`;

Deno.writeFile("data/mawpower.lua", new TextEncoder().encode(out));
console.log("updated: mawpower.lua");
