import { readCSVObjects } from "https://deno.land/x/csv@v0.8.0/mod.ts";

const f = await Deno.open("scripts/data/runeforgelegendaryability.csv");

const lines = [];
for await (const row of readCSVObjects(f)) {
  lines.push(`\t{ ${row.ID}, ${row.UnlockItemID} }`);
}

f.close();

const out = `local _, addon = ...;

-- This file is generated by the update script. Do not edit.

local runeforgelegendaryability = {
${lines.join(",\n")}
};

function addon.RuneforgeLegendaryGetPowerIDByUnlockItemID(itemID)
	for i = 1, #runeforgelegendaryability do
		local entry = runeforgelegendaryability[i];
		if (entry[2] == itemID) then
			return entry[1];
		end
	end
end
`;

Deno.writeFile("data/runeforgelegendaryability.lua", new TextEncoder().encode(out));
console.log("updated: runeforgelegendaryability.lua");
