import fetchDBC from "../utils/fetch-dbc.ts";

interface RuneforgeLegendaryAbility {
	Name_lang: string;
	ID: number;
	SpecSetID: number;
	InventoryTypeMask: number;
	SpellID: number;
	ItemBonusListID: number;
	PlayerConditionID: number;
	Field_9_0_1_34972_007: number;
	UnlockItemID: number;
	CovenantID: number;
	Field_9_1_0_38549_010: number;
}

const { build, data } = await fetchDBC<RuneforgeLegendaryAbility>("runeforgelegendaryability");

const out = `local _, addon = ...;

-- This file is generated by the update script. Do not edit.
-- Data based on build ${build}

local runeforgelegendaryability = {
${data.map((entry) => `\t{ ${entry.ID}, ${entry.UnlockItemID} }`).join(',\n')}
};

function addon.RuneforgeLegendaryGetPowerIDByUnlockItemID(itemID)
	for i = 1, #runeforgelegendaryability do
		local entry = runeforgelegendaryability[i];
		if (entry[2] == itemID) then
			return entry[1];
		end
	end
end
`;

Deno.writeFile("data/runeforgelegendaryability.lua", new TextEncoder().encode(out));
console.log("updated: runeforgelegendaryability.lua");
