if (WOW_PROJECT_ID ~= WOW_PROJECT_CLASSIC) then
    return
end

RAID_CLASS_COLORS["SHAMAN"]["r"] = 0.25
RAID_CLASS_COLORS["SHAMAN"]["g"] = 0.32
RAID_CLASS_COLORS["SHAMAN"]["b"] = 0.96
RAID_CLASS_COLORS["SHAMAN"]["colorStr"] = "ff4254f5"
